version: '3.1'

services:

  wordpress:
    image: replaceemailwithawsses
    container_name: replaceemailwithawsses_web
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    ports:
      - '8080:80'
    env_file:
      - ../.env
    volumes:
      - wordpress:/var/www/html
      - ../src/ReplaceEmailWithAwsSes.php:/var/www/html/wp-content/plugins/replace-email-with-aws-ses/ReplaceEmailWithAwsSes.php
      - ../vendor:/var/www/html/wp-content/plugins/replace-email-with-aws-ses/vendor

  db:
    image: mysql:8.0
    container_name: replaceemailwithawsses_db
    restart: always
    env_file:
      - ../.env
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
